[project]
name = "pypoe"
version = "0.3.0"
requires-python = ">=3.13"
dependencies = [
    "nicegui>=2.14.0",
    "keyboard>=0.13.5",
    "pyautogui>=0.9.54",
    "pynput>=1.8.2",
    "pyperclip>=1.11.0",
    "requests>=2.32.0",
    "websockets>=14.0",
    "pywebview>=5.1",
    "PySide6>=6.8",
    "qtpy>=2.4",
    "curl-cffi>=0.15.0",
    "pystray>=0.19.5",
    "pillow>=12.3.0",
]

[tool.uv]
python-preference = "only-managed"
override-dependencies = [
    "python3-xlib; sys_platform == 'never'"
]
